use_frameworks!
pod 'AFNetworking', '2.6.0'
pod 'Reachability', '3.2'
pod 'MarqueeLabel', '2.2.4'
pod 'SSKeychain', '1.2.3'
pod 'MMDrawerController', '0.6.0'
pod 'SDWebImage', '3.7.3'
pod 'youtube-ios-player-helper', '~> 0.1.4'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'RNBlurModalView', '0.1.0'
pod 'MRProgress', '0.8.2'
pod 'RNCryptor', '3.0.1'
pod 'GCDWebServer', '3.2.7'
pod 'NSData+Base64'
